### ISSUE TITLE
Unable to install v1.3.4

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/13th-age#20]
In GitLab by @gerry4 on Apr 25, 2020, 21:02

Receive red error bar on Systems page stating "Installation Failed: Not Found". This is when updating a previous version, and after uninstall and trying 1.3.4 from the FVTT installer, as well as pasting manifest link. 

FVTT: 0.5.5 via node.js
Host OS: Windows 10 Enterprise

Node console: nothing unusual
javascript console: 
```
foundry.js:22778 Error: Not Found
    at Request.<anonymous> (G:\Foundry47\resources\app\dist\files.js:1:3624)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.onRequestResponse (G:\Foundry47\resources\app\node_modules\request\request.js:1059:10)
    at ClientRequest.emit (events.js:311:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
```

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Apr 26, 2020, 14:03

closed
